### PR TITLE
docs: edited FAQs

### PR DESCRIPTION
**Pull request by freiburgermsu**

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@freiburgermsu Could you please edit the commits as mentioned in https://github.com/biosimulations/biosimulations/pull/3923#issuecomment-1002319581

**Comment by jonrkarr** [comment]
Some of the changes in this PR and others unintentionally change the meaning of the documentation. I will need to review the documentation.

**Comment by freiburgermsu** [comment]
@jonrkarr I apologize for misinterpreting your documentation, and not catching this earlier.

**Pull request merged**
