### PR TITLE
feat: add consent and analytics capabilities 

### PR DESCRIPTION
**Pull request by bilalshaikh42**
**What new features does this PR implement?**
Adds analytics service for analytics data to google analytics. 
Automatically manages user consent
adds information about different types of cookie s

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@jonrkarr  this still needs to be cleaned up, but all of the core implementation and logic are there. Could you check for any bugs/issues that you notice? 

Todo
- [x] Fill in placeholders for cookie types
- [x] add to simulators
- [x] add to dispatch
- [x] make module configurable (pass in the site-id)
- [x] add testing 
- [x] clean up styling of consent box
- [x] create cookie page in docs

**Comment by jonrkarr** [comment]
This looks nice. 

I pushed a couple changes
- Fixed grammar
- Polished style
- Contextualized app name
- Change docs links to full links (not actually necessary)
- Got tests working
- Fixed lint issue

I don't understand all of the categories. 
- What cookies are necessary?
- What cookies do we need to function?
- What cookies do we need for performance?

I think we want
- [ ] 1 category with 1 slider for service improvement
- [ ] A note that says we don't use tracking cookies with no corresponding slider

Also
- [x] Contextualize the name of the application (e.g, using `ConfigService.appName`)
- [x] Edit the discussion of cookies in https://docs.biosimulations.org/about/privacy/
- [x] Add https://docs.biosimulations.org/about/cookies/ page or change the link to https://docs.biosimulations.org/about/privacy

**Comment by bilalshaikh42** [comment]
> I don't understand all of the categories.

The categories are the standard categories defined by [GDPR](https://gdpr.eu/cookies/) and used by most of the consent management tools

> * What cookies are necessary?
> * What cookies do we need to function?
> * What cookies do we need for performance?

I have replaced the placeholders with some more helpful information that explains these.

> I think we want
> 
> * [ ]  1 category with 1 slider for service improvement
> * [ ]  A note that says we don't use tracking cookies with no corresponding slider

I was originally going to include just the cookies we want, but looking at all of the consent management systems, such as [onetrust](https://www.onetrust.com/forms/cookie-consent-demo-video/), they are all quite explicit about having the required cookies enabled. I paralleled this with the tracking cookies.  The cookie policy will need to explicitly list each cookie used in each category. For some, such as functional, we have been using local storage instead of cookies, but this should probably still be mentioned

**Comment by bilalshaikh42** [comment]
@jonrkarr  this is ready for merging with approval.

**Pull request merged**
