### PR TITLE
Only import languages needed for syntax highlighting

### LINKED ISSUE #1405: Only import languages needed for syntax highlighting
See instructions: https://www.npmjs.com/package/ngx-highlightjs

I tried to follow the instructions. The issue is the lack of typescript types for the individual languages. It would take me some time to figure out how to deal with this. I tried to follow the discussion [here](https://github.com/MurhafSousli/ngx-highlightjs/issues/115), but couldn't get it to work.

### PR DESCRIPTION
**Pull request by bilalshaikh42**
Fixes #1405

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
Is JSON the only language  needed currently?

**Comment by bilalshaikh42** [comment]
added dockerfile as well

**Review by jonrkarr — COMMENTED** [review]
Looks good. Thanks for figuring this out.

**Comment by bilalshaikh42** [comment]
> Looks good. Thanks for figuring this out.

Great. It should merge in automatically once approved.

**Review by jonrkarr — APPROVED** [review]

**Pull request merged**
