### PR TITLE
feat(platform): added validation for project ids

### LINKED ISSUE #3183: Add validation for projects
- [x] Id matches ^[a-zA-Z0-9_-]{3,}$
- [ ] simulationRun is the id of a valid run
- [ ] The status of that run was successful
- [ ] That run has at least one root level metadata document (uri with no slashes in it)

The UI does all such checking. But it should also be enforced at the database level so that the API cannot bypass these checks.

### PR DESCRIPTION
**Pull request by jonrkarr**
closes #3183

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
It might be better to add this validation to the controller level instead

**Comment by jonrkarr** [comment]
I leave it to you to move the validation

**Comment by bilalshaikh42** [comment]
> I leave it to you to move the validation

I kept both. The database validation is helpful for preventing mistakes made by the API code and the controller is user facing.

**Pull request merged**
