### PR TITLE
feat(combine-service): Add validation for Lems 

### PR DESCRIPTION
**Pull request by jonrkarr**
Also addresses part of #2633

### CODE REVIEW

**Comment by jonrkarr** [comment]
Can be merged once BioSimulators-utils 0.1.84 is released

**Comment by bilalshaikh42** [comment]
@jonrkarr let me know when we can merge. I'll rebase some of the commits before merging it in

**Comment by jonrkarr** [comment]
I think this is good to merge.

**Comment by bilalshaikh42** [comment]
Done in #2644

**Pull request closed without merging**
