### PR TITLE
Simulation status

### PR DESCRIPTION
**Pull request by bilalshaikh42**
I have added a intermediate status for simulation runs called "processing".

This is intended to indicate that the job has finished on the HPC and will the results will be available soon. This was previously indicated as "Completed". However, due to the asynchronous reading of files, the simulation run would get marked as completed before the results were uploaded.  Now, a simulation run is marked as completed only after the results have been updated. 

This should prevent some of the confusion and need to check for edge cases that was seen in #1881. This will NOT resolve the issue seen in #1797 as a run that does not produce any output will be marked as completed as soon as the dispatch service "uploads" the empty results.

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@jonrkarr Would this change cause any issues for the way you are outputting simulation progress? 
I don't think this needs to  be reflected in #1851, as I see that as a different measure of "progress" than the status here.

If this change looks okay, it should automatically merge in on approval.

**Comment by bilalshaikh42** [comment]
@jonrkarr Could you confirm that these changes are okay? This is ready to merge

**Comment by jonrkarr** [comment]
This is helpful. This addresses the issue Ion and I were discussing that the STATUS was set to SUCCEEDED before the results were available.

Regarding #1851, this makes a similar distinct between the status of tasks and outputs.  After a task finishes, its status will be SUCCEEDED (or FAILED), but the status of the outputs that it contributes to will be QUEUED (or RUNNING if the output also contains results from prior tasks). By the end of the execution of the entire COMBINE archive, the status of each task and output will be SUCCEEDED (or FAILED).

I see #1851 as somewhat distinct from the status and log that's currently implemented. The current status and log cover the entire creation, saving, and execution of a COMBINE archive. #1851 captures more detail about the execution. Since #1851 doesn't cover ever place where failures can occur, we still need this status and log. In #1851, I'm trying to use consistent terminology to what you've chosen, but I don't think we need to integrate the two types of logs together.

**Comment by bilalshaikh42** [comment]
> This is helpful. This addresses the issue Ion and I were discussing that the STATUS was set to SUCCEEDED before the results were available.
> 
> Regarding #1851, this makes a similar distinct between the status of tasks and outputs. After a task finishes, its status will be SUCCEEDED (or FAILED), but the status of the outputs that it contributes to will be QUEUED (or RUNNING if the output also contains results from prior tasks). By the end of the execution of the entire COMBINE archive, the status of each task and output will be SUCCEEDED (or FAILED).
> 
> I see #1851 as somewhat distinct from the status and log that's currently implemented. The current status and log cover the entire creation, saving, and execution of a COMBINE archive. #1851 captures more detail about the execution. Since #1851 doesn't cover ever place where failures can occur, we still need this status and log. In #1851, I'm trying to use consistent terminology to what you've chosen, but I don't think we need to integrate the two types of logs together.

Great, could you approve the PR? it should merge in automatically.

**Review by jonrkarr — APPROVED** [review]
Looks good. I see updated `apps/dispatch/src/app/services/simulation/simulation-status.service.ts` as well.

**Pull request merged**
