### PR TITLE
chore: added action to monitor todos

### LINKED ISSUE #4057: Find alternative to TODO bot
The to-do comments in the code are no longer added to the PRs. This was useful. Unfortunately, the app has shut down, but it should be replaceable with GithubActions.  In fact, we might just be able to fork it since it was built on [probot](https://github.com/probot/probot), which has  GitHub Actions based hosting options 

https://github.com/JasonEtco/todo/discussions/293

### PR DESCRIPTION
**Pull request by jonrkarr**
Closes #4057

Adds most popular action for monitoring todos
- Creates issues for new todos
- Closes issues for removed todos

This supports the languages were using:
- CSS
- HTML
- JavaScript, TypeScript
- Markdown
- Python 
  - Multiline in PR alstr/todo-to-issue-action#99
- SASS (PR alstr/todo-to-issue-action#100)
- SCSS (PR alstr/todo-to-issue-action#100)
- Shell
- YAML

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
We probably want to restrict the branch to dev to prevent opening issues for todos in PRs. The feature I found most helpful was adding a comment to a PR that contained todos so that they could be kept track of during the PR review, but this would at least address the issue portion

**Comment by jonrkarr** [comment]
Now restricted to dev branch.

**Comment by jonrkarr** [comment]
The action also aims to automatically close issues when associated todos are removed.

**Pull request merged**
