### PR TITLE
generate singularity images automatically

### LINKED ISSUE #1901: Simulation service can't handle spaces in names of COMBINE archive files
Example simulation #5ff6b5e92fcd3374d4f0236a.

The simulation service failed when the uploaded archive had the filename `test-bngl (2).omex`. The filename needs to be wrapped in `""`.

```
/var/spool/slurm/slurmd/job2629205/slurm_script: eval: line 17: syntax error near unexpected token `('
/var/spool/slurm/slurmd/job2629205/slurm_script: eval: line 17: `singularity run -B /home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/5ff6b5e92fcd3374d4f0236a/in:/root/in -B /home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/5ff6b5e92fcd3374d4f0236a/out:/root/out /home/FCAM/crbmapi/nfs/biosimulations/singularity_images/biosimulations_bionetgen_2.5.1.img -i /root/in/test-bngl (2).omex -o /root/out'
```

### PR DESCRIPTION
**Pull request by bilalshaikh42**
closes #1901

### CODE REVIEW

**Review by jonrkarr — COMMENTED** [review]
Good
- The Docker image URL looks good.
- The escaping of `omexName` looks good.

Question
- Where are the images getting pulled?

**Comment by bilalshaikh42** [comment]
> Good
> 
> * The Docker image URL looks good.
> * The escaping of `omexName` looks good.
> 
> Question
> 
> * Where are the images getting pulled?

The singularity run command will create the images as needed. They are cached in the home directory, similar to docker

**Comment by jonrkarr** [comment]
Will this check GHCR for a new version of the same tag? With Docker, its necessary to first run `docker pull ...`. While `docker run ...` will pull images if they don't exist locally, if there's an image with the tag in the local cache, docker will use this image even if a newer version exists in the image repository.

**Comment by bilalshaikh42** [comment]
> Will this check GHCR for a new version of the same tag? With Docker, its necessary to first run `docker pull ...`. While `docker run ...` will pull images if they don't exist locally, if there's an image with the tag in the local cache, docker will use this image even if a newer version exists in the image repository.

I had not considered that. I added in a singularity pull statement as well

**Comment by bilalshaikh42** [comment]
@jonrkarr should merge automatically on approval

**Review by jonrkarr — APPROVED** [review]
With the pull command, I think this should now work as we intended.

**Pull request merged**
