### PR TITLE
Update _redirects

### LINKED ISSUE #1374: Redirect https://run.biosimulations.org/api to https://run.biosimulations.org/api/ (add trailing slash)
https://run.biosimulations.org/api doesn't return anything. This should be re-directed to https://run.biosimulations.org/api/.

### PR DESCRIPTION
**Pull request by bilalshaikh42**
closes #1374

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
Need to test the netlify deployment and confirm that the redirect works

**Comment by jonrkarr** [comment]
The changes look good. This exactly what I meant.
```
/api  /api/
```

**Comment by bilalshaikh42** [comment]
Looking at the Netlify [documentaion](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash) I don't think this will work. The forward slash is being redirected properly already. Looking at the webconsole for  run.biosimulations.org/api the redirect does work properly, but the css and js files are not resolved

**Review by jonrkarr — CHANGES_REQUESTED** [review]
I see the issue now. It's not a redirection problem for `/api`. The page is blank because the browser isn't finding the cs and js files.

What's needed is a redirection for the css, js, and png files
- https://run.biosimulations.org/swagger-ui.css --> https://run.biosimulations.org/api/swagger-ui.css
- https://run.biosimulations.org/swagger-ui-bundle.js --> https://run.biosimulations.org/api/swagger-ui-bundle.js
- https://run.biosimulations.org/swagger-ui-standalone-preset.js --> https://run.biosimulations.org/api/swagger-ui-standalone-preset.js
- https://run.biosimulations.org/swagger-ui-init.js --> https://run.biosimulations.org/api/swagger-ui-init.js
- https://run.biosimulations.org/favicon-32x32.png --> https://run.biosimulations.org/api/favicon-32x32.png

I think these lines need to be added to `_redirects`
```
/swagger-ui.css                    /api/swagger-ui.css
/swagger-ui-bundle.js              /api/swagger-ui-bundle.js
/swagger-ui-standalone-preset.js   /api/swagger-ui-standalone-preset.js
/swagger-ui-init.js                /api/swagger-ui-init.js
/favicon-32x32.png                 /api/favicon-32x32.png
```

**Review by jonrkarr — APPROVED** [review]
Looks good

**Comment by jonrkarr** [comment]
@bilalshaikh42 I think this is ready for merging unless you need to test netlify.

**Comment by bilalshaikh42** [comment]
Closing this for later

**Pull request closed without merging**
