### PR TITLE
More flexible 2D visualization to better match needs of SED-ML L1V3 and BioModels

### LINKED ISSUE #2383: Disable CORS for Vega editors
- [x] https://vega.github.io/editor/
- [x] http://idl.cs.washington.edu/projects/lyra/app/

### PR DESCRIPTION
**Pull request by jonrkarr**
Adds more flexibility
- Grid of subplots
- Subplots can draw data from multiple SED-ML files or reports
- X data no longer restricted to be from a single SED data set

This is setup so that the plot configuration could relatively easily be driven by Plot2D outputs from SED-ML L1V3 to satisfy the expectations of BioModels, SED-ML, and their users. A few additional changes are needed:
- Simulation tools need to output data to HDF5 including VCell. This is relatively easy for the other tools because this can be changed in one place.
- This additional data needs to get stored into the database and read out. If simulation tools put the data in the same file (`report.h5`), no additional work is needed here.
- The above needs to be edited in the description of how simulation tools should work.
  - Tutorial
  - Standards
  - Simulator template repo
- We need a service to retrieve 2d plot configurations from SED-ML files. This could be done in JavaScript, but if we setup a service this would likely be easier than recreating COMBINE and SED-ML processing functionality in JavaScript.

Closes #2383.

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
Sorry, not sure why this was closed

**Review by bilalshaikh42 — CHANGES_REQUESTED** [review]
@jonrkarr We have actually diverged quite a bit here. My code is updated for the API, but I dont have the Sedml like datastructure. 
I dont quite follow some parts of the code for the multiple plots. Could you take a look at the merge?

**Comment by jonrkarr** [comment]
I'm working on merging this. I see there were conflicting changes particularly in `biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts`.

**Comment by jonrkarr** [comment]
A new version of one of the dependencies is causing trouble for me (see below). Have you experienced this?

I already tried deleting and re-build node_modules with `npm i`. I still get the same errors.

```
Error: ./node_modules/@nestjs/common/pipes/validation.pipe.js
Module not found: Error: Can't resolve 'class-transformer' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/@nestjs/common/pipes'

Error: ./node_modules/@nestjs/common/serializer/class-serializer.interceptor.js
Module not found: Error: Can't resolve 'class-transformer' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/@nestjs/common/serializer'

Error: ./node_modules/@nestjs/mapped-types/dist/type-helpers.utils.js
Module not found: Error: Can't resolve 'class-transformer/storage' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/@nestjs/mapped-types/dist'

Error: ./node_modules/cookie-signature/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/cookie-signature'

Error: ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/etag'

Error: ./node_modules/@nestjs/swagger/dist/swagger-module.js
Module not found: Error: Can't resolve 'fastify-swagger' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/@nestjs/swagger/dist'

Error: ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/destroy'

Error: ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/etag'

Error: ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/mime'

Error: ./node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/send'

Error: ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'http' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'http' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'http' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/content-disposition/index.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/content-disposition'

Error: ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/express/lib'

Error: ./node_modules/mime/mime.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/mime'

Error: ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/mime-types'

Error: ./node_modules/send/index.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/send'

Error: ./node_modules/serve-static/index.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/serve-static'

Error: ./node_modules/swagger-ui-dist/absolute-path.js
Module not found: Error: Can't resolve 'path' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/swagger-ui-dist'

Error: ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'stream' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/destroy'

Error: ./node_modules/send/index.js
Module not found: Error: Can't resolve 'stream' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/send'

Error: ./node_modules/body-parser/lib/read.js
Module not found: Error: Can't resolve 'zlib' in '/home/jonrkarr/Documents/Biosimulations/biosimulations/node_modules/body-parser/lib'
```

**Comment by bilalshaikh42** [comment]
This is happening because front end code is trying to use backed classes in
a way that is causing the front end to import the backend libraries. Do you
have a "type" specified in the backend, which is defined as some
modification to a "class" in the backend? If so, try changing the "type" to
a "class" as well.

**Comment by bilalshaikh42** [comment]
This is the reason that in my code I have used SimulationRunDatum[] as a
type directly rather than defining ''' type results = SimulationRunDatum[]
''' and then using results as the type.

**Comment by jonrkarr** [comment]
The issue is caused by the import you added for `@biosimulations/dispatch/api-model` into the visualization service. I commented this out and replace this with types (equal to `any`).

I merged with the `dev` branch. I basically kept my version of `view.component.ts`. Were there any key changes that you were trying to make?

Vega is now directly using URLs for dispatch REST API! Additional transformations are no longer necessary.

**Comment by jonrkarr** [comment]
I think this is ready to merge

**Review by bilalshaikh42 — DISMISSED** [review]

**Comment by bilalshaikh42** [comment]
> The issue is caused by the import you added for `@biosimulations/dispatch/api-model` into the visualization service. I commented this out and replace this with types (equal to `any`).

This is not a cope issue actually.  There is a particular issue when using "types" instead of "classes". The types cannot be imported properly for some reason. I can get the typing back in. Otherwise, there will be no warning if a api change breaks the front end.  

> I merged with the `dev` branch. I basically kept my version of `view.component.ts`. Were there any key changes that you were trying to make?
> 
> Vega is now directly using URLs for dispatch REST API! Additional transformations are no longer necessary.
All the changes to view component were to use the new datamodel

**Comment by jonrkarr** [comment]
> This is not a cope issue actually. There is a particular issue when using "types" instead of "classes". The types cannot be imported properly for some reason. I can get the typing back in. Otherwise, there will be no warning if a api change breaks the front end.

That would be great.

**Review by bilalshaikh42 — APPROVED** [review]

**Pull request merged**
