### PR TITLE
feat(dispatch-api,auth): required permissions to get metadata for all run, documented APIs

### LINKED ISSUE #3035: Require permissions to read metadata about all simulation runs

### LINKED ISSUE #3036: Add documentation for `outputId` route parameter of dispatch API
@bilalshaikh42 do you know how this can be documented with nest?

### LINKED ISSUE #3037: Add documentation for REST API operations

### LINKED ISSUE #3040: Add favicons to Swagger apps for all APIs
- [x] simulators
- [x] ontologies
- [x] platform

### PR DESCRIPTION
**Pull request by jonrkarr**
- closes #3035
- closes #3036 
- closes #3037
- closes #3040

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
This change breaks the platform front end since it is using the metadata endpoint for now

**Comment by bilalshaikh42** [comment]
This also prevents the api from starting up due to missing dependencies

**Comment by jonrkarr** [comment]
Its important to keep unpublished projects private. Our example simulations can be published. The platform should not display other simulations.

The `getAllMetadata` method and associated endpoint could be restricted to published projects. In that case, the permissions can be removed.

**Pull request merged**
