### PR TITLE
refactor(combine-api): changed to use configuration for new temporary S3 bucket

### LINKED ISSUE #4058: Change combine api temporary storage bucket
Google cloud buckets only support lifecycle methods on a bucket wide scope. 

Therefore, the combine API must use a separate bucket than the main storage for temporary files

### PR DESCRIPTION
**Pull request by jonrkarr**
Closes #4058 

- Aligned names of configuration variables used by `apps/combine-api` with `config/` and the deployment repository
- Removed key prefix for temporary storage; no longer needed because a separate bucket is used
- Renamed method and tool for deleting temporary COMBINE to align with terminology for config variables (temporary archives vs any temporary file)
- Formatted Python code in `config/`
- Cleaned up printing in `config`

Related changes in deployment repo: [d02ef0cce0bab7b789866e4e70e21e8ef9f9f7ba](https://github.com/biosimulations/deployment/commit/d02ef0cce0bab7b789866e4e70e21e8ef9f9f7ba).

### CODE REVIEW

**Comment by jonrkarr** [comment]
@bilalshaikh42 It looks like you've set up the temp buckets and set their retention policies. Please merge if these are ready to use.

**Comment by bilalshaikh42** [comment]
@jonrkarr are the failing tests okay?

**Review by bilalshaikh42 — APPROVED** [review]

**Comment by jonrkarr** [comment]
The failing tests relate to pyNeuroML. If you want to merge, I can fix that in another PR.

**Comment by jonrkarr** [comment]
Looks like the test failure was transient. It appeared to be an issue with xvfb.

**Pull request merged**
