### PR TITLE
a few edits

### PR DESCRIPTION
**Pull request by freiburgermsu**

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@freiburgermsu Thanks for these!  could you edit the PR titles and commit messages on these/other PRs to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) style? That will make it easier to keep track of changes and auto-merge these in once the checks pass

**Review by bilalshaikh42 — APPROVED** [review]
Looks good pending fixing the title/commit

**Comment by freiburgermsu** [comment]
@bilalshaikh42 Let me know if anything must still be done with any of these commits. I won't blast your alerts with any more of my messages tonight.

**Pull request merged**
