### PR TITLE
fixed: results URLs for charts

### LINKED ISSUE #2960: RunBioSimulations Vega and Plotly visualizations are broken
Requests for data are not properly URI encoded.

### PR DESCRIPTION
**Pull request by jonrkarr**
Closes #2960

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
TIL 
Thanks! Does the encode URIComponent need to be called at the input to the function as well?

**Comment by bilalshaikh42** [comment]
Also the platform/account api are failing since I revoked the password they were using. Should be fine to merge in if those two are the only failures

**Comment by jonrkarr** [comment]
I've also gotten `encodeURI` and `encodeURIComponent` mixed up. `encodeURI` sounds like what you want, but you actually want `encodeURIComponent`.

**Pull request merged**
