### PR TITLE
User serialize

### PR DESCRIPTION
**Pull request by bilalshaikh42**
supersedes #201

### CODE REVIEW

**Comment by jonrkarr** [comment]
I'm seeing this error which is preventing the user profile page from loading:

https://crbm-api.herokuapp.com/users/jonrkarr
```
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```

**Comment by bilalshaikh42** [comment]
> I'm seeing this error which is preventing the user profile page from loading:
> 
> https://crbm-api.herokuapp.com/users/jonrkarr
> 
> ```
> {
>   "detail": "No authorization token provided",
>   "status": 401,
>   "title": "Unauthorized",
>   "type": "about:blank"
> }
> ```

What route is giving that error? Could you try to log out and relogin?

**Comment by bilalshaikh42** [comment]
> > I'm seeing this error which is preventing the user profile page from loading:
> > https://crbm-api.herokuapp.com/users/jonrkarr
> > ```
> > {
> >   "detail": "No authorization token provided",
> >   "status": 401,
> >   "title": "Unauthorized",
> >   "type": "about:blank"
> > }
> > ```
> 
> What route is giving that error? Could you try to log out and relogin?

I see a potential issue. The backend has an error the first time a user logs in. Should be fixed now.
I dont think that would cause a 401 but a 404 though, so might not be the cause

**Comment by jonrkarr** [comment]
The error is from `/user/` -- the page that should display the profile

**Comment by jonrkarr** [comment]
(1) After login https://crbm-api.herokuapp.com/users is called twice. First, successfully with no response.
```
Request URL: https://crbm-api.herokuapp.com/users
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 3.231.91.211:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization, content-type
Access-Control-Allow-Methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Access-Control-Allow-Origin: http://localhost:4200
Allow: POST, GET, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Thu, 19 Dec 2019 04:28:09 GMT
Server: nginx/1.16.1
Vary: Origin
Via: 1.1 vegur
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Headers: authorization,content-type
Access-Control-Request-Method: POST
Connection: keep-alive
Host: crbm-api.herokuapp.com
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```
Second, unsuccessfully
```
Request URL: https://crbm-api.herokuapp.com/users
Request Method: POST
Status Code: 400 BAD REQUEST
Remote Address: 3.231.91.211:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:4200
Connection: keep-alive
Content-Length: 118
Content-Type: application/problem+json
Date: Thu, 19 Dec 2019 04:28:09 GMT
Server: nginx/1.16.1
Vary: Origin
Via: 1.1 vegur
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJqRkNPVGd4UXpNNU5UaEROa1U1TkVGRlJEUXlSalF5UlVJek5UbERSakEzUlRnNFJUWXhSZyJ9.eyJpc3MiOiJodHRwczovL2NyYm0uYXV0aDAuY29tLyIsInN1YiI6ImdpdGh1YnwyODQ4Mjk3IiwiYXVkIjpbImFwaS5iaW9zaW11bGF0aW9ucy5vcmciLCJodHRwczovL2NyYm0uYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU3NjcyOTY4OCwiZXhwIjoxNTc2ODE2MDg4LCJhenAiOiIwTktNamJadWV4a0NnZldZM0JHOUMzODA4WXNkTFVyYiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.dnxlgwAHOC7cc12GYAUISDkwQvQ_FNWn9YuntKBHoesGGQraja1tuXF8tIUi77A1I3FLyhOeLkVKDg_nC_EQRy6CWjv0qvtvxFfHGs5rmFj4_6kcsqBTJTrgfpcqdIJGGO4M9SimaBz7H_dSI-KRLTUnVQ_YULIwst5pmJ1VX8klJ-3CFJjQwNt5FDz49rGcohksTNrJ_dZlFloujJ77Jky_q3fByIqwRn1V5Oefbfe7bNQcsWdyAd_IFTYgzr3L3m5w88JJ46xOWwoX-ZZG9rGAPoIE4ljJhU86cwLRFb7SYMGdsGUo8DF8k8m6JMaCnLvrLsJWSq_PJ75g0nENWQ
Connection: keep-alive
Content-Length: 117
Content-Type: application/json
Host: crbm-api.herokuapp.com
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
{_id: "github|2848297", userName: "jonrkarr", email: "jonrkarr@gmail.com", emailVerified: false,…}
email: "jonrkarr@gmail.com"
emailPublic: false
emailVerified: false
userName: "jonrkarr"
_id: "github|2848297"
```
with this response
```
{
  "detail": "'userId' is a required property",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

**Comment by jonrkarr** [comment]
On navigation to the profile page (`/user/`), https://crbm-api.herokuapp.com/users/jonrkarr is called twice. First, successfully with no response.

```
Request URL: https://crbm-api.herokuapp.com/users/jonrkarr
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 34.236.76.223:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization
Access-Control-Allow-Methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Access-Control-Allow-Origin: http://localhost:4200
Allow: PUT, GET, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Thu, 19 Dec 2019 04:30:55 GMT
Server: nginx/1.16.1
Vary: Origin
Via: 1.1 vegur
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET
Connection: keep-alive
Host: crbm-api.herokuapp.com
Origin: http://localhost:4200
Referer: http://localhost:4200/user
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```

Second unsuccessfully
```
Request URL: https://crbm-api.herokuapp.com/users/jonrkarr
Request Method: GET
Status Code: 404 NOT FOUND
Remote Address: 34.236.76.223:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:4200
Connection: keep-alive
Content-Length: 12
Content-Type: application/json
Date: Thu, 19 Dec 2019 04:30:55 GMT
Server: nginx/1.16.1
Vary: Origin
Via: 1.1 vegur
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJqRkNPVGd4UXpNNU5UaEROa1U1TkVGRlJEUXlSalF5UlVJek5UbERSakEzUlRnNFJUWXhSZyJ9.eyJpc3MiOiJodHRwczovL2NyYm0uYXV0aDAuY29tLyIsInN1YiI6ImdpdGh1YnwyODQ4Mjk3IiwiYXVkIjpbImFwaS5iaW9zaW11bGF0aW9ucy5vcmciLCJodHRwczovL2NyYm0uYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU3NjcyOTY4OCwiZXhwIjoxNTc2ODE2MDg4LCJhenAiOiIwTktNamJadWV4a0NnZldZM0JHOUMzODA4WXNkTFVyYiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.dnxlgwAHOC7cc12GYAUISDkwQvQ_FNWn9YuntKBHoesGGQraja1tuXF8tIUi77A1I3FLyhOeLkVKDg_nC_EQRy6CWjv0qvtvxFfHGs5rmFj4_6kcsqBTJTrgfpcqdIJGGO4M9SimaBz7H_dSI-KRLTUnVQ_YULIwst5pmJ1VX8klJ-3CFJjQwNt5FDz49rGcohksTNrJ_dZlFloujJ77Jky_q3fByIqwRn1V5Oefbfe7bNQcsWdyAd_IFTYgzr3L3m5w88JJ46xOWwoX-ZZG9rGAPoIE4ljJhU86cwLRFb7SYMGdsGUo8DF8k8m6JMaCnLvrLsJWSq_PJ75g0nENWQ
Connection: keep-alive
Host: crbm-api.herokuapp.com
Origin: http://localhost:4200
Referer: http://localhost:4200/user
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```
with this response
"Not Found"

**Comment by bilalshaikh42** [comment]
This was silly of me. The latest api had not been deployed to heroku. 
Should now be up

**Pull request merged**
