### PR TITLE
Clean up

### LINKED ISSUE #1057: Fix Builds, CI, CD and Organize dependencies
# Builds and Tests
## Apps 
- [x] Account
- [x] Account-API
- [x] Platform
- [x] Platform-API
- [x] Dispatch
- [x] Dispatch-API
- [x] Dispatch-Service

### Auth
- [x] Angular
- [x] Common
- [x] Nest

### Config 
- [x] Angular
- [x] Common
- [x] Nest

### Shared
- [x] Icons
- [x] UI
- [x] Debug
- [x] Styles
- [x] Assets
- [x] Datamodel
- [x] Environments
- [ ] Messaging

### Account
- [ ] Datamodel
- [ ] Auth Zero

### Platform
- [x] Database
- [x]  API
- [x] View

### Dispatch
- [x] Datamodel

# CI CD
## Github
- [x] Update cloud token 
- [x] Fix Git Hub action to test changes properly
- [ ] Add Docker file build test 
- [ ] Build and push Docker image on tags

## Dockerhub
- [x] Update Cloud Token
- [x] Correct App Names

## Netlify
- [x] Update Cloud token 
- [x] Correct App names

### LINKED ISSUE #1234: Simulator view does not reset to main tab on version change
**Please describe the bug**

On the view simulators page, selecting a different version does not reset the tab group to the main tab

**Please describe how to reproduce the bug**

1. Go to www.biosimulators.org/simulators/copasi
2. Click on versions
3. Select a version other than the lates
4. While the data does update, the versions tab is still selected

**How should BioSimulations have behaved**

The view should switch to the main tab

**Additional context**

This is probably a problem with the biosimulations-tab group wrapper. Since the url parameter change is detected at a containing component, it must not be getting passed down. The component might need to include a listener for url changes. expose the underlying mat-tab group to allow for the index to be changed manually.

### LINKED ISSUE #1275: get name from ontology service
https://github.com/biosimulations/Biosimulations/blob/29e2057aa7d4d792ee19f333cea2f329f7559932/biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts#L177-L182

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 29e2057aa7d4d792ee19f333cea2f329f7559932. It&#x27;s been assigned to @bilalshaikh42 because they committed the code.

### LINKED ISSUE #1278: Correct text copied when Docker pull command button is clicked
When the button is clicked (under the overview tab), the following is copied:
```
docker pull { image }
```

It should be
```
docker pull docker.io/biosimulators/Biosimulations_tellurium:2.4.1
```

Example: https://biosimulators.org/simulators/tellurium/latest

### LINKED ISSUE #1279: Remove right column from versions tab of simulator pages
Example:
https://biosimulators.org/simulators/tellurium/latest

The right column (pull command, license, website) for a specific version might be confused with the meta data for the individual versions. Lets remove the column to eliminate this potential source of confusion.

Instead
- Add a "Copy to clipboard" button to the "Image" column of the versions table

### LINKED ISSUE #1288: Add feedback for button clicks in UI
**Is your feature request related to a problem? Please describe.**
On the simulators homepage, when clicking on the simulators button, the application appears to be unresponsive before navigating.  See #1289
**Please describe the solution you'd like**

When I click the button, it should provide feedback that the click was registered.  Reintroducing the ripple effect for navigation buttons might be a good way to approach it

**Please describe alternatives you've considered**
As mentioned in #1289  we can fix this  particular problem by ensuring that the simulator page is preloaded. But this is a more general problem of not having sufficient feedback on button clicks that may have a delay in response. Button should generally include feedback. 

@jonrkarr  thoughts on re-enabling the ripple?

### LINKED ISSUE #1294: move this to its own library. Can be used across apps
https://github.com/biosimulations/Biosimulations/blob/2ec9b0206141861d3d2cd40b3589ff51e80b0f9a/biosimulations/apps/simulators/src/app/MarkedPreloadingStrategy.ts#L2-L7

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 2ec9b0206141861d3d2cd40b3589ff51e80b0f9a. It&#x27;s been assigned to @bilalshaikh42 because they committed the code.

### LINKED ISSUE #1309: Highlight container version in versions table
Table in the "Versions" tab at `https://biosimulators.org/simulators/{ simulator-id }/`.

### LINKED ISSUE #1314: Add JWS online logo to biosimulations

### PR DESCRIPTION
**Pull request by bilalshaikh42**
closes #1279, closes #1278, closes #1288, closes #1309, closes #1275, closes #1314, closes #1234

### CODE REVIEW

**Comment by jonrkarr** [comment]
These issues, and other issues, are already fixed in the dev-simulators branch. I'll initiate the pull request

**Comment by bilalshaikh42** [comment]
Includes commits from #1318

**Review by jonrkarr — APPROVED** [review]
Looks good

**Comment by jonrkarr** [comment]
Also closes #1288, closes #1309, closes #1275, closes #1314, closes #1234

Looks ready to merge

**Pull request merged**
