### PR TITLE
chore(combine-service): restored dynamic reference to logging schemas in ApiCurio

### PR DESCRIPTION
**Pull request by jonrkarr**
This just reorders the schemas in the spec file

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
Should this now trigger a rebuild of the combine-api-client library? Would be good to confirm that works correctly

**Comment by bilalshaikh42** [comment]
> Should this now trigger a rebuild of the combine-api-client library? Would be good to confirm that works correctly

Does seem like it ran, but there were no changes to commit

**Comment by jonrkarr** [comment]
There shouldn't be any changes to commit. The schemas are just in a different order in the YAML file to be in sync with what ApiCurio outputs.

The change here is really in ApiCurio. In ApiCurio, the CombineArchiveLog schema is intended to be linked to the the OpenAPI spec for the API (`https://api.biosimulations.org/openapi.json#/components/schemas/...`) to avoid defining schemas twice. When I edited the spec manually to separate the types of each response, I started from the de-referenced schema and forgot to maintain this reference. This restores that reference.

**Pull request merged**
