### PR TITLE
fix: failures for template format, docs and openapi-client gen actions

### LINKED ISSUE #4656: 🐛: final merge Github actions fail for format, documentation and openapi generation
### Contact Details

schaff.jim@gmail.com

### Location

BioSimulations

### What happened?

final merge Github actions fail for format, documentation and openapi generation - maintenance is required.

### What made it happen?

I loaded the page!

### Version

Development (Deployed on a .dev domain)

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jcschaff**
**What new features does this PR implement?**
no new features

**What bugs does this PR fix?**
fixes the following actions which fire upon merge or release:
1. Update Combine API
2. Update Documentation
3. Continuous Integration (Format Job and Update Sitemap Job) 

**Does this PR introduce any additional changes?**
Please summarize any additional changes that this PR introduces.

* updates python and node versions in some actions
* relaxes linting rules for generated openapi client for Angular

**How have you tested this PR?**
tested openapi generation and linting locally - no formal tests.

**Additional information**
None.

### CODE REVIEW

**Comment by jcschaff** [comment]
debugging the PR-merge related github actions (e.g. openapi-generation, template formatting (should be moved to lint), and building the sitemap.

Need an approval to test some actions unless I make them able to be initiated manually.

**Comment by jcschaff** [comment]
am pushing updated combine-api openapi clients for nestjs and angular (will still be generated in CI), but wanted to debug it locally.  Got the sed scripts to work on macos to make development easier.

**Review by eagmon — APPROVED** [review]
Looks great @jcschaff!

**Review by moraru — COMMENTED** [review]
Humpty Dumpty is back together again :)

**Pull request merged**
