### PR TITLE
Karr/dev logging

### LINKED ISSUE #1666: Provide API data models in JSON schema format
Outputting this as a JSON schema would be helpful for promoting the data model as a "standard" beyond just the input format for BioSimulators.

- [ ] Use this package https://www.npmjs.com/package/@openapi-contrib/openapi-schema-to-json-schema to generate JSON schema file from OpenAPI spec. 
  - Save the file to `biosimulations/libs/shared/assets/src/assets/`. 
  - Implement as dev tool in `biosimulations/tools"
- [ ] Add execution of this tool to CI workflow
  - Generate JSON schema file
  - Commit and push to repo
- [ ] Add links to schema to documentation
 - `biosimulations/apps/simulators/src/app/standards/simulator-specs/simulator-specs.component.html`

### PR DESCRIPTION
**Pull request by jonrkarr**
- Updated documentation for logging COMBINE/OMEX archives
- Added endpoint for JSON schema version of `Simulator` schema 
  - Will be served at https://api.biosimulators.org/schema/Simulator.json
  - The same can be set up for other key schemas that the community needs to interact with such as the schema for logs of the execution of COMBINE archives.
  - Addresses #1666.

Still todo 
- [ ] Implement data model in typescript
    - [ ] Interface
    - [x] Database model
    - [ ] API model
- [ ] Add JSON schema endpoint for schema for logs of the execution of COMBINE/OMEX archives -- uncomment code in `apps/dispatch-api/src/main.ts`. Will close #1666.

### CODE REVIEW

**Comment by jonrkarr** [comment]
I started a data model for logs in `libs/dispatch/api-models/src/lib/simulationRunLog.ts`.

This is what I'm trying to implement -- more clearly articulated without the Mongoose or Swagger decorators.
```typescript
export enum Status {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export interface Exception {
  category: string;
  message: string;
}

export interface Log {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
}

export interface SedOutputLog extends Log {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
}

export interface SedReportLog extends SedOutputLog {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
  dataSets: {[dataSetId: string]: Status};
}

export interface SedPlot2DLog extends SedOutputLog {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
  curves: {[curveId: string]: Status};
}

export interface SedPlot3DLog extends SedOutputLog {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
  surfaces: {[surfaceId: string]: Status};
}

export interface SedTaskLog extends Log {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
}

export interface SedDocumentLog extends Log {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
  tasks: {[taskId: string]: SedTaskLog};
  outputs: {[outputId: string]: SedOutputLog};
}

export interface CombineArchiveLog extends Log {
  status: Status;
  exception: Exception;
  skipReason: Exception;
  output: string;
  duration: number;
  sedDocuments: {[sedDocumentId: string]: SedDocumentLog};
}
```

There's four example log files here: 
https://github.com/biosimulations/Biosimulations/tree/karr/dev-logging/biosimulations/apps/simulators/src/app/standards/simulation-logs

**Comment by bilalshaikh42** [comment]
~~If this is currently passing, I think its best to merge in now. This contains a lot of documentation changes which I would like to keep as a separate PR from any changes/addition  to the datamodel.~~

I was looking at an older version where the specs were not yet included.

**Comment by bilalshaikh42** [comment]
Is this ready to merge?

**Review by bilalshaikh42 — APPROVED** [review]

**Comment by jonrkarr** [comment]
This was fine to merge. 

Note, the data model for logs isn't yet connected to any other component. That's why I didn't merge it myself.

**Pull request merged**
