### PR TITLE
working on parameterzing allowed hosts to environment (product, dev, …

### PR DESCRIPTION
**Pull request by jonrkarr**
…test); setting login/logout redirect URLs based on environment

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
To confirm, running development locally will not be possible against the current production api. Is there a need for this?

**Comment by jonrkarr** [comment]
No, I don't need to run the API locally.

My changes only partially address this todo. Until their are multiple deployments of the APIs, the issue can't be fully addressed.

**Comment by jonrkarr** [comment]
@bilalshaikh42 this is ready for merging

**Comment by bilalshaikh42** [comment]
This will be preventing local  development frontends from querying the api. I don't see a reason to do that. I did overlook the redirect URI however. I can include that change in the next push

**Comment by jonrkarr** [comment]
Access from localhost is still allowed. Eventually this access should be removed. But this can't be removed yet.

This also fixes an issue with the login/logout redirect URLs

**Pull request closed without merging**
