### PR TITLE
Fix build errors and add OmexFile / SimulationSpec types to dispatch service

### PR DESCRIPTION
**Pull request by gmarupilla**

### CODE REVIEW

**Comment by gmarupilla** [comment]
@bilalshaikh42 tested dispatch with `nx test` and `nx build` on my local machine, working just fine, with all required changes. Workflows are failing due to other services that's why I had to test on local.

**Comment by bilalshaikh42** [comment]
Hey, the code looks good. But it seems that the branch is including many overwritten commits. 
Could you please create a new branch from the current dev and include your changes only?

**Comment by bilalshaikh42** [comment]
I can include these changes actuallly. I will raise a pr shortly

**Comment by gmarupilla** [comment]
@bilalshaikh42 will you be merging this after api and biosimulation changes are done? Or are there any changes that you want to request before merging?

**Pull request merged**
